### ISSUE TITLE
[Bug]: SpatiePermission

### ISSUE THREAD

**Issue by MKWebDesign** [hugomyb/filament-error-mailer#2]
### What happened?

this plugin interacts with the FilamentSpatieRolesPermissionsPlugin, it disables it in the side navigation. this happens when the order of the  plugins in the adminpanelprovider is:
->plugin(
                    FilamentErrorMailerPlugin::make(),
                    FilamentSpatieRolesPermissionsPlugin::make(),
Putting the FilamentErrorMailerPlugin at the end of the list solved the problem.

### How to reproduce the bug

When i place the the plugin on top of the list in the adminpanalprovider, like this:
->plugin(
                    FilamentErrorMailerPlugin::make(),
                    FilamentSpatieRolesPermissionsPlugin::make(),
The the FilamentSpatieRolesPermissionsPlugin is not visible in the left navigation bar. removing the plugin in the list or putting it at the end of the list saves the problem.

### Package Version

2

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by hugomyb** [comment]
Hi @MKWebDesign , 

I have no idea why my plugin interacts this way with SpatiePermission but thanks for letting me know, and for posting your solution.
